# Generated by Django 4.2.11 on 2026-02-07 18:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=255)),
                ('donor_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('donor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pet_name', models.CharField(help_text='Name of the pet this donation is for', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('online', 'Online Payment'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=255, null=True)),
                ('donation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'db_table': 'donations',
                'ordering': ['-donation_date'],
            },
        ),
    ]
